# Generated by Django 3.2.9 on 2021-11-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_auto_20211123_2019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitante',
            table='visitante',
        ),
    ]
