# Generated by Django 3.2.9 on 2021-11-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitante',
            options={'verbose_name': ('Visitante',), 'verbose_name_plural': ('Visitantes',)},
        ),
        migrations.AlterModelTable(
            name='visitante',
            table='visitantes',
        ),
    ]
